name: CI

on: 
  push:
      branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install
    # js 파일 빌드
    - name: Build source file
      run: npm run build
    # Docker hub 로그인
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PW }}
    # 도커이미지 빌드, 푸시
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: kopi2642/iesay
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    # 기존에 생성한 IAM 유저로 로그인
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    # 배포 생성
    - name: Create CodeDeploy Deployment
      id: deploy
      run: |
        aws deploy create-deployment \
          --application-name ${{ secrets.AWS_DEPLOY_APP_NAME }} \
          --deployment-group-name ${{ secrets.AWS_DEPLOY_GROUP }}  \
          --deployment-config-name ${{ secrets.AWS_DEPLOY_CONFIG }} \
          --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
