name: CI

on: 
  push:
      branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install
    # js 파일 빌드
    - name: Build source file
      run: npm run build
    # Docker hub 로그인
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PW }}
    # 도커이미지 빌드, 푸시
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: kopi2642/iesay
